config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.in2p3.fr/opsportal/eosc-opsportal:
      branch: master
      repo: https://gitlab.in2p3.fr/opsportal/eosc-opsportal.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.in2p3.fr/opsportal/eosc-opsportal git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-ecru-balinese.sh
        container: qc.acc_hasty-ecru-ant
  QC.Doc:
    repos:
      gitlab.in2p3.fr/opsportal/eosc-opsportal find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-asparagus-bandicoot.sh
        container: qc.doc_squeaky-pumpkin-audemer
      gitlab.in2p3.fr/opsportal/eosc-opsportal git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-champagne-tetra.sh
        container: qc.doc_geeky-blue-argentino
      gitlab.in2p3.fr/opsportal/eosc-opsportal markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-ochre-moorhen.sh
        container: qc.doc_droopy-wisteria-numbat
  QC.Lic:
    repos:
      gitlab.in2p3.fr/opsportal/eosc-opsportal licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-rose-dhole.sh
        container: qc.lic_cozy-teal-barnacle
  QC.Sty:
    repos:
      gitlab.in2p3.fr/opsportal/eosc-opsportal hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lemon-chihuahua.sh
        container: qc.sty_slimy-viridian-slug
      gitlab.in2p3.fr/opsportal/eosc-opsportal jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sapphire-cockroach.sh
        container: qc.sty_tacky-green-chipmunk
  QC.Ver:
    repos:
      gitlab.in2p3.fr/opsportal/eosc-opsportal get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-pear-bear.sh
        container: qc.ver_grumpy-rust-seal
timeout: 5400
